### ISSUE TITLE
Use dataclass.asdict() for namcouple types

### ISSUE THREAD

**Issue by valentinaschueller** [uwefladrich/rdy2cpl#23]
Is there a reason why you implemented `as_dict()` for each dataclass in [types.py](https://github.com/uwefladrich/rdy2cpl/blob/main/rdy2cpl/namcouple/types.py), instead of using [`dataclasses.asdict()`](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict)? 

I checked and at a glance, I do not see any case where the methods you implemented would behave differently from the default implementation. But I might have overlooked something!

**Comment by valentinaschueller** [comment]
If all goes well, you should be able to get rid of all the `as_dict()` definitions in `types.py`.
Then, add `from dataclasses import as_dict` in `scriptengine_task.py` and change [l. 46](https://github.com/uwefladrich/rdy2cpl/blob/7f486e4a95ecac7666cdd89bad35e59b73b16b9d/rdy2cpl/scriptengine_task.py#L46) to:
```python
f.write(yaml.safe_dump(asdict(namcouple)))
```

**Comment by uwefladrich** [comment]
Very good catch! I did not know about ``dataclasses.asdict()`` and in particular I did not expect any "built-in" variant to handle things recursively (which is what we need here).
I agree, it looks like we could get rid of ``*.as_dict``. I will try in a branch!

**Comment by uwefladrich** [comment]
I did an ECE4 test run with #24 and it worked well. So I guess I can merge the change.
